name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Setup linters
        run: |
          sudo apt-get update
          sudo apt-get install luarocks
          sudo luarocks install luacheck
      - name: Run luacheck
        run: |
          make lint
